language: node_js

node_js: 8

cache: yarn

branches:
  only:
  - master

before_deploy:
  - yarn build

deploy:
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN
  project: "ask-a-dev-marketing"
